#!/usr/bin/env node
/**
 * Automated accessibility pass for the ValEV site.
 *
 * Starts (or reuses) a Next.js dev server, visits every route, and runs
 * axe-core against each page. Also runs two targeted checks that axe's
 * generic rules can under- or over-report on:
 *   - contrast of --silver-lo (#9AA0A8) text against its actual rendered
 *     background, walking up the DOM to find the effective opaque bg
 *   - the rendered hit-area of every <input type="range"> slider, at a
 *     mobile viewport, since native slider thumbs are UA-styled and
 *     weren't visually verified in the code-only audit.
 *
 * Read-only: does not modify application code. Prints a structured
 * report to stdout; A11Y-FINDINGS.md is a human-curated summary of a run
 * of this script, not auto-generated by it.
 *
 * Usage:
 *   node a11y/axe-audit.mjs                # starts its own dev server
 *   BASE_URL=http://localhost:3000 node a11y/axe-audit.mjs   # reuse a running server
 */
import { chromium } from 'playwright'
import AxeBuilder from '@axe-core/playwright'
import { spawn } from 'node:child_process'
import http from 'node:http'

const ROUTES = [
  '/',
  '/about',
  '/technology',
  '/contact',
  '/partner',
  '/partner/franchise',
  '/partner/host',
  '/partner/fleet',
  '/privacy',
  '/terms',
]

const PORT = 4173
const EXTERNAL_BASE_URL = process.env.BASE_URL
const BASE_URL = EXTERNAL_BASE_URL ?? `http://127.0.0.1:${PORT}`

const AXE_TAGS = ['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa']

function waitForServer(url, timeoutMs = 90_000) {
  const start = Date.now()
  return new Promise((resolve, reject) => {
    const attempt = () => {
      const req = http.get(url, res => {
        res.resume()
        resolve()
      })
      req.on('error', () => {
        if (Date.now() - start > timeoutMs) {
          reject(new Error(`Server at ${url} did not become ready within ${timeoutMs}ms`))
        } else {
          setTimeout(attempt, 500)
        }
      })
    }
    attempt()
  })
}

async function startDevServer() {
  console.log(`Starting dev server on port ${PORT}...`)
  const child = spawn('npx', ['next', 'dev', '-p', String(PORT)], {
    cwd: new URL('..', import.meta.url).pathname,
    stdio: 'pipe',
  })
  child.stderr.on('data', d => process.stderr.write(`[next] ${d}`))
  await waitForServer(BASE_URL)
  console.log('Dev server ready.\n')
  return child
}

// WCAG relative luminance / contrast ratio, mirroring axe-core's own math.
function srgbToLinear(c) {
  const cs = c / 255
  return cs <= 0.03928 ? cs / 12.92 : Math.pow((cs + 0.055) / 1.055, 2.4)
}
function relativeLuminance([r, g, b]) {
  return 0.2126 * srgbToLinear(r) + 0.7152 * srgbToLinear(g) + 0.0722 * srgbToLinear(b)
}
function contrastRatio(rgbA, rgbB) {
  const lA = relativeLuminance(rgbA)
  const lB = relativeLuminance(rgbB)
  const lighter = Math.max(lA, lB)
  const darker = Math.min(lA, lB)
  return (lighter + 0.05) / (darker + 0.05)
}

async function auditSilverLoContrast(page) {
  return page.evaluate(() => {
    function parseRgb(str) {
      const m = str.match(/rgba?\(([^)]+)\)/)
      if (!m) return null
      const parts = m[1].split(',').map(s => parseFloat(s.trim()))
      return { r: parts[0], g: parts[1], b: parts[2], a: parts.length > 3 ? parts[3] : 1 }
    }
    function effectiveBackground(el) {
      let node = el
      while (node) {
        const cs = getComputedStyle(node)
        const bg = parseRgb(cs.backgroundColor)
        if (bg && bg.a > 0.98) return { rgb: [bg.r, bg.g, bg.b], node }
        node = node.parentElement
      }
      return { rgb: [7, 8, 10], node: null } // fall back to --bg-hero/site base
    }

    const TARGET = 'rgb(154, 160, 168)' // #9AA0A8 == --silver-lo
    const results = []
    const all = document.querySelectorAll('body *')
    for (const el of all) {
      if (!(el.textContent && el.textContent.trim())) continue
      const cs = getComputedStyle(el)
      if (cs.color !== TARGET) continue
      // Only count elements whose direct text (not just descendants') is this color,
      // to avoid duplicate parent/child reporting.
      const ownText = Array.from(el.childNodes).some(n => n.nodeType === 3 && n.textContent.trim())
      if (!ownText) continue

      const rect = el.getBoundingClientRect()
      if (rect.width === 0 || rect.height === 0) continue

      const fontSizePx = parseFloat(cs.fontSize)
      const fontWeight = parseInt(cs.fontWeight, 10) || 400
      const isLargeText = fontSizePx >= 24 || (fontSizePx >= 18.66 && fontWeight >= 700)

      const { rgb: bgRgb } = effectiveBackground(el.parentElement ?? el)
      results.push({
        text: el.textContent.trim().slice(0, 60),
        tag: el.tagName.toLowerCase(),
        fontSizePx: Math.round(fontSizePx * 100) / 100,
        fontWeight,
        isLargeText,
        bgRgb,
        selector:
          el.id ? `#${el.id}` : el.className ? `${el.tagName.toLowerCase()}.${String(el.className).split(' ').join('.')}` : el.tagName.toLowerCase(),
      })
    }
    return results
  }).then(rawResults =>
    rawResults.map(r => {
      const ratio = contrastRatio([154, 160, 168], r.bgRgb)
      const required = r.isLargeText ? 3.0 : 4.5
      return {
        ...r,
        bgHex: '#' + r.bgRgb.map(c => Math.round(c).toString(16).padStart(2, '0')).join(''),
        ratio: Math.round(ratio * 100) / 100,
        required,
        passesAA: ratio >= required,
      }
    })
  )
}

async function auditRangeSliders(page) {
  const rects = await page.evaluate(() => {
    return Array.from(document.querySelectorAll('input[type="range"]')).map(el => {
      const rect = el.getBoundingClientRect()
      const cs = getComputedStyle(el)
      return {
        id: el.id || null,
        ariaLabel: el.getAttribute('aria-label'),
        width: Math.round(rect.width),
        height: Math.round(rect.height),
        cssHeight: cs.height,
        cssPadding: cs.padding,
      }
    })
  })
  return rects
}

async function run() {
  let serverProcess = null
  if (!EXTERNAL_BASE_URL) {
    const alreadyUp = await new Promise(resolve => {
      const req = http.get(BASE_URL, res => {
        res.resume()
        resolve(true)
      })
      req.on('error', () => resolve(false))
    })
    if (!alreadyUp) {
      serverProcess = await startDevServer()
    } else {
      console.log(`Reusing server already running at ${BASE_URL}\n`)
    }
  }

  const browser = await chromium.launch()

  const report = {
    routes: [],
    contrastFindings: [],
    sliderFindings: [],
  }

  try {
    for (const route of ROUTES) {
      const url = `${BASE_URL}${route}`
      console.log(`\n=== ${route} ===`)

      // Desktop pass: full axe scan.
      const desktopContext = await browser.newContext({ viewport: { width: 1440, height: 900 } })
      const desktopPage = await desktopContext.newPage()
      await desktopPage.goto(url, { waitUntil: 'networkidle' })

      const axeResults = await new AxeBuilder({ page: desktopPage }).withTags(AXE_TAGS).analyze()

      const contrast = await auditSilverLoContrast(desktopPage)
      report.contrastFindings.push({ route, results: contrast })

      console.log(`  axe violations: ${axeResults.violations.length}`)
      for (const v of axeResults.violations) {
        console.log(`    [${v.impact}] ${v.id}: ${v.help} (${v.nodes.length} node(s))`)
        for (const n of v.nodes.slice(0, 5)) {
          console.log(`        - ${n.target.join(' ')}`)
          if (n.failureSummary) console.log(`          ${n.failureSummary.split('\n').join(' ')}`)
        }
      }
      if (axeResults.incomplete.length) {
        console.log(`  axe incomplete (needs review): ${axeResults.incomplete.length}`)
        for (const v of axeResults.incomplete) {
          console.log(`    [${v.id}] ${v.help} (${v.nodes.length} node(s))`)
          for (const n of v.nodes.slice(0, 5)) {
            console.log(`        - ${n.target.join(' ')}`)
          }
        }
      }

      const failingSilverLo = contrast.filter(c => !c.passesAA)
      if (failingSilverLo.length) {
        console.log(`  silver-lo contrast failures: ${failingSilverLo.length}`)
        for (const c of failingSilverLo) {
          console.log(
            `    "${c.text}" (${c.tag}, ${c.fontSizePx}px/${c.fontWeight}) on ${c.bgHex}: ratio ${c.ratio} < required ${c.required}`
          )
        }
      } else if (contrast.length) {
        console.log(`  silver-lo contrast: ${contrast.length} element(s) checked, all pass AA`)
      }

      await desktopContext.close()

      // Mobile pass: slider touch targets.
      const mobileContext = await browser.newContext({ viewport: { width: 375, height: 812 }, hasTouch: true })
      const mobilePage = await mobileContext.newPage()
      await mobilePage.goto(url, { waitUntil: 'networkidle' })
      const sliders = await auditRangeSliders(mobilePage)
      if (sliders.length) {
        console.log(`  range sliders (mobile viewport): ${sliders.length}`)
        for (const s of sliders) {
          const flag = s.height < 24 ? '  <-- below 24px WCAG 2.5.8 minimum' : ''
          console.log(`    id=${s.id ?? '(none)'} rect=${s.width}x${s.height}px cssHeight=${s.cssHeight}${flag}`)
        }
        report.sliderFindings.push({ route, sliders })
      }
      await mobileContext.close()

      report.routes.push({
        route,
        violations: axeResults.violations,
        incomplete: axeResults.incomplete,
        passes: axeResults.passes.length,
      })
    }
  } finally {
    await browser.close()
    if (serverProcess) serverProcess.kill()
  }

  console.log('\n\n=== SUMMARY ===')
  let totalViolations = 0
  for (const r of report.routes) {
    totalViolations += r.violations.length
    console.log(`${r.route}: ${r.violations.length} violation(s), ${r.incomplete.length} incomplete, ${r.passes} passed checks`)
  }
  console.log(`\nTotal violations across all routes: ${totalViolations}`)

  process.exitCode = totalViolations > 0 ? 1 : 0
}

run().catch(err => {
  console.error(err)
  process.exitCode = 1
})
